version: '3'

services:
  strapi:
    build: .
    ports:
      - '1337:1337'
    environment:
      DATABASE_CLIENT: postgres
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_NAME: strapidb
      DATABASE_USERNAME: strapi
      DATABASE_PASSWORD: strapi123
    depends_on:
      - postgres

  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: strapidb
      POSTGRES_USER: strapi
      POSTGRES_PASSWORD: strapi123
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
